### ISSUE TITLE
cannot see nav item with IE11

### ISSUE THREAD

**Issue by BhoneyKim** [thienpow/svecart#1]
![image](https://user-images.githubusercontent.com/9066602/83498448-e5a61b80-a4f6-11ea-9b0a-1f06411a071f.png)
any plan to solve it?

**Comment by thienpow** [comment]
i don't have access to IE11... using macbook

maybe try add the following to global.css in static folder see if it works.

`
.navbar.navbar-default {
    width: 100%;
}
`

**Comment by BhoneyKim** [comment]
@thienpow suggested solution doesn't work on IE11.
I've been struggling with IE11 compatible on svelte and still have no idea for it.
Using Babel or Bublé seem like an solution, though i can't apply them on this sapper project.

Could you try those (Babel or Bublé)-integration?
